### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/osveijer-task-8#1]
**Sorrrrrii Oliver!**

But you really did not observe that the _High-to-low_ routines should be global declarations, just as the C functions are global. This requires you to:
1) Declare `multiply` and `fakultet` as global. _Hint_: search for the `globl` directive.
2) Follow the callee convensions. A callee must preserve the values of any utilized saved registers and the return address register using the stack.
_Stack operation macros_:
```mips
##
# Push value to application stack.
# PARAM: Registry with value.
##
.macro	PUSH (%reg)
	addi	$sp,$sp,-4              # decrement stack pointer (stack builds "downwards" in memory)
	sw	    %reg,0($sp)             # save value to stack
.end_macro

##
# Pop value from application stack.
# PARAM: Registry which to save value to.
##
.macro	POP (%reg)
	lw	    %reg,0($sp)             # load value from stack to given registry
	addi	$sp,$sp,4               # increment stack pointer (stack builds "downwards" in memory)
.end_macro
```

Otherwise, your _Sieve of Eratosthenes_ was fully acceptable!

Good luck!

**Comment by Hellyhoken** [comment]
Hope i fixed everything.

**Comment by violaso** [comment]
Thanks!
